### PR TITLE
Smoke Detector

### LINKED ISSUE #51: Please support the smoke detector for fire detection and siren
It would be nice to get the Information (event) if the smoke detector detect a fire. This information could be important for existing devices in OpenHAB like open the shutters or push notifications to the mobile phone or external gong in the garden.

In addition to that I wish a switch to start the alarm siren. For example if a burglar enters the house, I would like to start the siren. 

Device: https://www.bosch-smarthome.com/uk/en/shop?url=products/smart-system-solutions/smoke-detector

### PR DESCRIPTION
**Pull request by coeing**
Closes #51

### CODE REVIEW

**Comment by coeing** [comment]
@GerdZanker @stefan-kaestle I was only able to implement it following the official API of the smoke detector service (https://apidocs.bosch-smarthome.com/local/#/Services/get_devices__deviceId__services_SmokeDetectorCheck). So I am not really sure if it works. Does any of you have a smoke detector or twin guard at home to test it? Otherwise I would suggest to merge it and let one of our users test it who has a smoke detector or twin guard.

It should be possible to:
- Trigger a smoke check by sending a PlayPause command with `Play` to the `smoke-check` channel of the thing
- Get the state of the last smoke check from the thing in the `smoke-check` channel

**Comment by GerdZanker** [comment]
>Does any of you have a smoke detector or twin guard at home to test it? 

I have both at home, but will not be able to test it before mid of August.

**Comment by coeing** [comment]
Okay, I will merge it into the next version then after you had time to test, no stress! :)

**Comment by GerdZanker** [comment]
PR content is now merge with a [new pull request](https://github.com/openhab/openhab-addons/pull/13760) for openHab 3.4 
The openhab code base changed a lot and it is easier now to get smaller parts merged to main branch.

I will continue step by step with other pending content of this repository and create future pull requests.

Thank you @coeing for providing the initial code.

**Pull request closed without merging**
