### PR TITLE
Wall Thermostat

### LINKED ISSUE #25: Add handler for "Wall thermostat" (temperature + humidity)
The Bosch Thermostat for floor heating system does also measure the relative air moisture and shares this with the controller. 

As a second iteration obtaining this value together with the temperature would be good to use for analytics and graphing.

### PR DESCRIPTION
**Pull request by coeing**
Closes #25

### CODE REVIEW

**Comment by stefan-kaestle** [comment]
Code looks good, don't have a wall thermostat, so can't test :-)

**Review by stefan-kaestle — APPROVED** [review]

**Comment by tuxianerDE** [comment]
@stefan-kaestle @coeing I can do the test since I have two of them running here would require an updated binary file though.

**Comment by coeing** [comment]
@tuxianerDE Thanks for your offer! I will build a new jar file this week with this feature in it :)

**Review by GerdZanker — COMMENTED** [review]
Code looks fine.
A first short tests with a locally compiled JAR resulted in a

    [WARN ] [ore.thing.internal.ThingRegistryImpl] - Cannot create thing. No binding found that supports creating a thing of type 'boschshc:wall-thermostat'.

and the device is ``UNINITIALIZED``. Therefore I want to take more test time before approval.

**Comment by coeing** [comment]
> Code looks fine.
> A first short tests with a locally compiled JAR resulted in a
> 
> ```
> [WARN ] [ore.thing.internal.ThingRegistryImpl] - Cannot create thing. No binding found that supports creating a thing of type 'boschshc:wall-thermostat'.
> ```
> 
> and the device is `UNINITIALIZED`. Therefore I want to take more test time before approval.

Oh, it is possible that I forgot adding the new handler to our Factory :O Good thing you tested it ;) Will have a look at it tomorrow!

**Comment by coeing** [comment]
@GerdZanker Added the wall thermostat handler to our handler factory, now it should be usable :)

**Review by GerdZanker — APPROVED** [review]
Works now for me

**Comment by GerdZanker** [comment]
I setup just one Wallthermostat and openhab received the humidity and temperature value of it.
Together with the device discovery I will do more tests, will all of my wall thermostats.

**Pull request merged**
